version: '3'
networks:
    kbs_network:
        external: true

services:
    # PG Database Migrator
    pgmigrator:
        image: kylinsystems/kbs-pgmigrator:${KBS_TAG}
        container_name: kbs-pgmigrator
        build:
            context: .
        environment:
            KBS_SEEDDB_NAME: ${KBS_SEEDDB_NAME}
            KBS_DB_HOST: ${KBS_DB_HOST}
            KBS_DB_PORT: ${KBS_DB_PORT}
            KBS_DB_NAME: ${KBS_DB_NAME}
            KBS_DB_USER: ${KBS_DB_USER}
            KBS_DB_PASS: ${KBS_DB_PASS}
        networks:
            kbs_network:
                aliases:
                    - kbs-pgmigrator
