{
 "title": "KBS-Cloud - Server Overview",
 "description": "System And Docker Monitoring Template",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes{}) - sum(node_memory_MemFree_bytes{}+node_memory_Buffers_bytes{}+node_memory_Cached_bytes{}) ) / sum(node_memory_MemTotal_bytes{}) * 100"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg  (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "Filesystem usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - 100 * sum(node_filesystem_free_bytes{}) / sum(node_filesystem_size_bytes{}) "
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": " (time()-process_start_time_seconds{instance=\"manager-001:9100\"})/86400"
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(rate(container_last_seen{job=\"cadvisor\", name!=\"\"}[5m]))"
    }
   ]
  },
  {
   "title": "Host cpu usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Host memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100*(node_memory_MemTotal_bytes{} - node_memory_MemFree_bytes{} - node_memory_Buffers_bytes{} - node_memory_Cached_bytes{}) / node_memory_MemTotal_bytes{} ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Host disk usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - 100 * ( sum by (instance) (node_filesystem_free_bytes{}) /sum  by (instance) (node_filesystem_size_bytes{}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Server Data",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "node_uname_info{job=\"node-exporter\"}"
    }
   ]
  },
  {
   "title": "Host Network I/O",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,device) (rate(node_network_receive_bytes_total{device!~\"^(lo|docker|veth|flannel|virbr).*\"}[1m]))",
     "legendFormat": "-> {{ instance}} {{ device }}"
    }
   ]
  }
 ]
}