version: '3'
networks:
    default:
        external:
            name: kbs_network

# volumes:
#   kbs_portainer_data:
#     external: true

services:
  portainer:
    image: portainer/portainer:1.23.1
    container_name: kbs-portainer
    restart: always
    ports:
      - ${PORT_PORTAINER}:9000
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - kbs_portainer_data:/data
    networks:
        default:
            aliases:
                - kbs-portainer
    labels: # NOT WORKING!!! ###
        - "traefik.enable=true"
        - "traefik.http.services.portainer.loadbalancer.server.port=9000"
        - "traefik.http.routers.portainer.rule=PathPrefix(`/portainer`)"
        - "traefik.http.routers.portainer.entrypoints=http"
        - "traefik.http.routers.portainer.middlewares=portainer-stripprefix"
        - "traefik.http.middlewares.portainer-stripprefix.stripprefix.prefixes=/portainer"
