version: '3'

networks:
    default:
        external:
            name: kbs_core

volumes:
  kbs_portainer_data:
    external: true

services:
  portainer:
    image: portainer/portainer:1.23.1
    container_name: kbs-portainer
    restart: always
    ports:
      - ${PORT_PORTAINER}:9000
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - kbs_portainer_data:/data
    networks:
        default:
            aliases:
                - kbs-portainer
