version: '3'
networks:
    default:
        external:
            name: kbs_network_pgcluster

services:
    pgweb:
        image: kylinsystems/kbs-pgweb:${KBS_TAG}
        container_name: kbs-pgweb
        restart: always
        build: 
            context: .
        environment:
            LISTEN_PORT: 8080
            PG_HOST_NAME: ${KBS_DB_HOST}
            PG_HOST_PORT: ${KBS_DB_PORT}
            PG_DB: ${KBS_DB_NAME}
            PG_USER: ${KBS_DB_USER_RO}
            PG_PASSWORD: ${KBS_DB_PASS_RO}
            PGWEB_AUTH_USER: pgweb
            PGWEB_AUTH_PASS: pgweb
        ports:
            - ${PORT_PGWEB}:8080
        networks:
            default:
                aliases:
                    - kbs-pgweb
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.pgweb.loadbalancer.server.port=8080"
            - "traefik.http.routers.pgweb.rule=PathPrefix(`/pgweb`)"
            - "traefik.http.routers.pgweb.entrypoints=http"
