version: '3'
networks:
    default:
        external:
            name: kbs_core

services:
    pgweb:
        image: kylinsystems/kbs-pgweb:${KBS_TAG}
        container_name: kbs-pgweb
        restart: always
        build: 
            context: .
        environment:
            LISTEN_PORT: 8080
            PG_HOST_NAME: ${KBS_DB_HOST}
            PG_HOST_PORT: ${KBS_DB_PORT}
            PG_DB: ${KBS_DB_NAME}
            PG_USER: ${KBS_DB_USER}
            PG_PASSWORD: ${KBS_DB_PASS}
            PGWEB_AUTH_USER: pgweb
            PGWEB_AUTH_PASS: pgweb
        ports:
            - 9020:8080
        networks:
            default:
                aliases:
                    - kbs-pgweb

