version: '3'
networks:
    default:
        external:
            name: kbs_network

# volumes:
#   pw2_pg:
#     external: true
#   pw2_influx:
#     external: true
#   pw2_grafana:
#     external: true
#   pw2_config:
#     external: true

services:
  pgwatch:
    image: cybertec/pgwatch2:1.7.0
    container_name: kbs-pgwatch
    restart: unless-stopped
    environment:
      - PW2_TESTDB=true
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/pgwatch
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    ports:
        - ${PORT_PGWATCH_DASHBOARD}:3000
        - ${PORT_PGWATCH_ADMINWEBUI}:8080
    # volumes:
    #   - pw2_pg:/var/lib/postgresql
    #   - pw2_influx:/var/lib/influxdb
    #   - pw2_grafana:/var/lib/grafana
    #   - pw2_config:/pgwatch2/persistent-config
    networks:
        default:
            aliases:
                - kbs-pgwatch
