version: '3.7'

networks:
    default:
        external:
            name: kbs_core

services:
    kbs_server:
        image: kylinsystems/kbs-server-eclipse:${KBS_TAG}
        container_name: kbs-server
        environment:
            KBS_DEBUG: ${KBS_DEBUG}
            DB_HOST: ${KBS_DB_HOST}
            DB_PORT: ${KBS_DB_PORT}
            DB_NAME: ${KBS_DB_NAME}
            DB_USER: ${KBS_DB_USER}
            DB_PASS: ${KBS_DB_PASS}
            DB_ADMIN_PASS: postgres
        build:
            context: .
            dockerfile: Server.Eclipse.Dockerfile
        ports:
            - ${PORT_KBS}:8080
            - 4554:4554 # debug
        networks:
            default:
                aliases:
                    - kbs-server
        # labels:
        #     - "traefik.enable=true"
        #     - "traefik.http.services.kbs_server.loadbalancer.server.port=8080"
        #     - "traefik.http.routers.kbs_server.rule=PathPrefix(`/app`) || Path(`/`) || PathPrefix(`/;jsessionid`) || PathPrefix(`/osgi/system/console`)"
        #     - "traefik.http.routers.kbs_server.entrypoints=http"


    # kbs_server:
    #     image: kylinsystems/kbs-server-karaf:${KBS_TAG}
    #     container_name: kbs-server
    #     environment:
    #         TZ: "Asia/Shanghai"
    #     build:
    #         context: .
    #         dockerfile: Server.Karaf.Dockerfile
    #     ports:
    #         - ${PORT_KBS}:8080
    #         - 5005:5005
    #     networks:
    #         default:
    #             aliases:
    #                 - kbs-server
