version: '3'
networks:
    default:
        external:
            name: kbs_network

services:
    kbs_server:
        image: kylinsystems/kbs-server-eclipse:${KBS_TAG}
        container_name: kbs-server
        restart: always
        environment:
            IDEMPIERE_APP_DEBUG: "true"
        build:
            context: .
            dockerfile: Server.Eclipse.Dockerfile
        ports:
            - 8080:8080
            - 8443:8443
            - 4554:4554 # debug
        networks:
            default:
                aliases:
                    - kbs-server
        # labels:
        #     - "traefik.enable=true"
        #     - "traefik.port=8080"
        #     - "traefik.docker.network=kbs_network"
        #     - "traefik.http.routers.kbs_server.rule=PathPrefix(`/app`)"
        #     - "traefik.http.routers.kbs_server.entrypoints=http"

    # kbs_server:
    #     image: kylinsystems/kbs-server-karaf:${KBS_TAG}
    #     container_name: kbs-server
    #     restart: always
    #     build:
    #         context: .
    #         dockerfile: Server.Karaf.Dockerfile
    #     # ports:
    #     #     - 8080:8080
    #     #     - 5005:5005
    #     networks:
    #         default:
    #             aliases:
    #                 - kbs-server
