version: '3'
networks:
    default:
        external:
            name: kbs_network

services:
    # PG Database Standalone
    pgserver:
        image: kylinsystems/kbs-pgsingle:${KBS_TAG}
        container_name: kbs-pgserver
        restart: always
        build:
            context: .
        ports:
            - ${PORT_PGSERVER}:${KBS_DB_PORT}
        networks:
            default:
                aliases:
                    - kbs-pgserver
        # logging:
        #     driver: "gelf"
        #     options:
        #         gelf-address: "udp://localhost:12201"
        #         tag: pgserver
        