version: '3.7'
networks:
    default:
        external:
            name: kbs_core

volumes:
    kbs_pg_data:
        external: true

services:
    # PG Database Standalone
    pgserver:
        image: postgres:11.8
        container_name: kbs-pgserver
        restart: always
        environment:
            - TZ=Asia/Shanghai
            - POSTGRES_PASSWORD=postgres
        ports:
            - 5432:5432
        volumes:
            - kbs_pg_data:/var/lib/postgresql/data
        networks:
            default:
                aliases:
                    - kbs-pgserver
