version: '3'
networks:
    default:
        external:
            name: kbs_core

services:
    # PG Database Standalone
    pgserver:
        image: kylinsystems/kbs-pgsingle:${KBS_TAG}
        container_name: kbs-pgserver
        restart: always
        build:
            context: .
        environment:
            KBS_DB_NAME: ${KBS_DB_NAME}
            KBS_DB_USER: ${KBS_DB_USER}
            KBS_DB_PASS: ${KBS_DB_PASS}
        ports:
            - 5432:5432
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 10
        networks:
            default:
                aliases:
                    - kbs-pgserver
