route:
    receiver: 'slack'

receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            text: "{{ .CommonAnnotations.description }}"
            username: 'ken.longnan'
            channel: '#general'
            api_url: 'https://hooks.slack.com/services/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'
