version: '3'
networks:
    default:
        external:
            name: kbs_core

services:
    backupper:
        image: kylinsystems/kbs-pgbackupper:${KBS_TAG}
        container_name: kbs-pgbackupper
        build:
            context: .
        restart: always
        volumes:
            - "./archives:/data"
        environment:
            BACKUP_NAME_1: backup_db
            SCHEDULE_1: '*/5 * * * *'
            BACKUP_DB_HOST_1: ${KBS_DB_HOST}
            BACKUP_DB_PORT_1: ${KBS_DB_PORT}
            BACKUP_DB_NAME_1: ${KBS_DB_NAME}
            BACKUP_DB_USER_1: ${KBS_DB_USER}
            BACKUP_DB_PASSWORD_1: ${KBS_DB_PASS}
            BACKUP_OPTIONS_1: '-C --compress=9'
            BACKUP_DIR_1: '/data/backup_db'
        networks:
            default:
                aliases:
                    - kbs-backupper
