version: '3.7'

networks:
    default:
        external:
            name: kbs_core

services:
  pgadmin4:
    image: dpage/pgadmin4:5.2
    container_name: kbs-pgadmin4
    restart: always
    ports:
      - "${PORT_PGADMIN4}:80"
    environment:
        PGADMIN_DEFAULT_EMAIL: 'pgadmin4@local.host'
        PGADMIN_DEFAULT_PASSWORD: 'pgadmin4'
    networks:
        default:
            aliases:
                - kbs-pgadmin4
