version: '3'

networks:
    default:
        external:
            name: kbs_core

services:
  pgadmin4:
    image: dpage/pgadmin4:4.21
    container_name: kbs-pgadmin
    restart: always
    ports:
      - "${PORT_PGADMIN4}:80"
    environment:
        PGADMIN_DEFAULT_EMAIL: 'pgadmin4@local.com'
        PGADMIN_DEFAULT_PASSWORD: 'pgadmin4'
    networks:
        default:
            aliases:
                - kbs-pgadmin4
